### ISSUE TITLE
Differentiate between a file GW does not support or cannot be processed.

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/cs-k8s-api#110]
fix that problem with the Glasswall Cloud SDK not being able to tell the difference between a file GW doesn't support and a file the engine can't process

**Comment by GINAGC** [comment]
@mohitsengarr this one can be fixed using the minio version only.

**Comment by Lestat06** [comment]
Tested with cs-api-0.1.17 and the endpoint give me the same result with a file that is not supported and from a file Known with issues that the engine cant process.
I can share file in channel since its a doc file and github apparently doesn't support to attach it here. FYI @samarthdd

**Comment by llmsjraj** [comment]
> Tested with cs-api-0.1.17 and the endpoint give me the same result with a file that is not supported and from a file Known with issues that the engine cant process.
> I can share file in channel since its a doc file and github apparently doesn't support to attach it here. FYI @samarthdd
> output:
> `{ "errors": [ "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n <title>Policy Issue</title>\n</head>\n<body>\n <h1>Document Access Blocked due to Policy</h1>\n The file does not comply with the current policy\n <br>\n The file id blocked is:\n <strong>de3c12b5-92bc-4b4f-98a8-8f4c17420766</strong>\n <br />\n <p>\n For more information contact your system administrator\n <hr>\n </p>\n</body>\n</html>" ], "status": "GW_FAILED" }`

@Lestat06 it seems you are testing GW Cloud SDK that is deployed with Classic-ICAP but this has to be tested with minio-icap.

**Comment by mohitsengarr** [comment]
> Tested with cs-api-0.1.17 and the endpoint give me the same result with a file that is not supported and from a file Known with issues that the engine cant process.
> I can share file in channel since its a doc file and github apparently doesn't support to attach it here. FYI @samarthdd
> output:
> `{ "errors": [ "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n <title>Policy Issue</title>\n</head>\n<body>\n <h1>Document Access Blocked due to Policy</h1>\n The file does not comply with the current policy\n <br>\n The file id blocked is:\n <strong>de3c12b5-92bc-4b4f-98a8-8f4c17420766</strong>\n <br />\n <p>\n For more information contact your system administrator\n <hr>\n </p>\n</body>\n</html>" ], "status": "GW_FAILED" }`

@Lestat06 it seems you are testing GW Cloud SDK that is deployed with Classic-ICAP but this has to be tested with minio-icap.

**Comment by mohitsengarr** [comment]
@Lestat06  please check this comment https://github.com/k8-proxy/cs-k8s-api/pull/211#issue-660055806

**Comment by Lestat06** [comment]
@mohitsengarr run with minio-icap
-unsupported file -->output: `GW_UNPROCESSABLE`
-DOC file with issues that machine cant process-->output: `GW_UNPROCESSABLE`
`{"errors":[],"status":"GW_UNPROCESSED","rebuildProcessingStatus":"UNPROCESSABLE"}`

-Files that cannot be processed/fail to rebuild-->output: `GW_ERROR`
e.g `{"errors":["Error Processing 'input' d42f5c96-c13d-417d-b7ed-74688c2b4966 and error detail is Object reference not set to an instance of an object."],"status":"GW_ERROR"}`

e.g `{"errors":[],"status":"GW_ERROR"}`

p.s this was tested with cdr-f2f

**Comment by samarthdd** [comment]
<img width="530" alt="Screenshot 2021-06-04 at 9 56 26 PM" src="https://user-images.githubusercontent.com/64204445/120834667-f57c9380-c580-11eb-97e2-08e50366355f.png">
<img width="546" alt="Screenshot 2021-06-04 at 10 01 53 PM" src="https://user-images.githubusercontent.com/64204445/120834677-f8778400-c580-11eb-9e2e-e8edbf4c2e83.png">

I can see CLEANED status  in logs
I can see from swagger or response UNPROCESSED 

<img width="1425" alt="Screenshot 2021-06-04 at 10 06 11 PM" src="https://user-images.githubusercontent.com/64204445/120834853-35437b00-c581-11eb-8383-fb9fcca94d11.png">


Not able to get expired , clean, INTERNALL_ERROR

Additionally  we are seeing GW Error in minio-go-sdk

This is not there in classic

<img width="1315" alt="Screenshot 2021-06-04 at 10 08 10 PM" src="https://user-images.githubusercontent.com/64204445/120835032-7045ae80-c581-11eb-9194-b14cf8340b62.png">

@mohitsengarr to clarify. This GW Error happens when a file like double extension or some anomaly files are sent.

**Comment by mohitsengarr** [comment]
@samarthdd are you sure that you are verifying the status based on the fileID between the logs and cs-k8s-api? and  regarding the expired , clean, INTERNALL_ERROR.
you will see the expired when the GW Engine license has expired.
you will see the INTERNALL_ERROR when there was an error in Minio-Icap processing.
you will not see the clean status as for the success case we are returning the sanitized file binary.

Also, please let me know for which file and api you are receiving the "Object reference not set to an instance of an object error"?

**Comment by samarthdd** [comment]
I have sent the files and scenario to replicate this issue
