### ISSUE TITLE
Some PDF files crashes swagger when trying to get the base64 of file on Cloud SDK classic

### ISSUE THREAD

**Issue by Lestat06** [k8-proxy/cs-k8s-api#452]
This happens in all endpoints that process base64.
in endpoints that accept /file, pdf file gets rebuild.
file to replicate 
[20090707-WAF-v0.1.pdf](https://github.com/k8-proxy/cs-k8s-api/files/6759118/20090707-WAF-v0.1.pdf)

**Comment by Lestat06** [comment]
found more info on this.
it happens with files thare are larger than 2mb
[7300-owctd-briefing-slides.pdf7300-owctd-briefing-slides.pdf](https://github.com/k8-proxy/cs-k8s-api/files/6763740/7300-owctd-briefing-slides.pdf7300-owctd-briefing-slides.pdf)
[surfstitch-group-limited---noni-b--asx-announcements.pdf](https://github.com/k8-proxy/cs-k8s-api/files/6763760/surfstitch-group-limited---noni-b--asx-announcements.pdf)

**Comment by Lestat06** [comment]
@mohitsengarr the popup looks good,
however i see it also in https also after uploading the large files, which i guess is good. if u click `wait` the base64 gets copied on clipboard, however when u paste it to the `base64:` variable the page crashes again.
actually can we add the reason why page is not responsive sth like
**" Page unrensponive due to base64 code being too large"** or something in between? so that this is clear its not sth from the api
![image](https://user-images.githubusercontent.com/6232283/125332750-b395f880-e349-11eb-9dc7-2afcb47288c1.png)
FYI @GINAGC

**Comment by mohitsengarr** [comment]
@Lestat06 this is due to the browser tabs memory limit. Data is too big to support this by the browser. It's not related to the cs-k8s-api.

**Comment by mohitsengarr** [comment]
You can test the api with other tools like Postman

**Comment by Lestat06** [comment]
yeah i understand this is due to the size of base64 i just though there is a workaround as for the site.
However is crashing postam too

**Comment by GINAGC** [comment]
@mohitsengarr can you check this one, why it is crashing postman?

**Comment by mohitsengarr** [comment]
@Lestat06 can you please share the postman screenshot and file that is crashing the postman? @GINAGC

**Comment by Lestat06** [comment]
files send on slack

**Comment by mohitsengarr** [comment]
@Lestat06 Postman is hanged to handled the base64 of 119MB file. Postman isn't crashing due to the cs-api but it can't handle the large base64 in it's request body. However, Postman is able to process the 119MB file.

![image](https://user-images.githubusercontent.com/43764140/125842684-fd3602c4-55d2-4b7f-a107-c3556c769a7f.png)

Swagger UI is broken due to the same and browser shown the OutOfMemory problem for that tab. Here, again due to the limitation of the memory for the perticular tab. You can go through this if that works for you. But I don't find any workaround for the same.

However, API can handle that big file too using the file endpoints instead of base64.

@GINAGC

**Comment by Lestat06** [comment]
@GINAGC there is not much we can do here with these large base64.
we can get the base64 from swagger but still it will crash when we paste into the request body due to memory inavailability of the browser
