### ISSUE TITLE
ZIP with 15+ files fails to rebuild

### ISSUE THREAD

**Issue by Lestat06** [k8-proxy/cs-k8s-api#470]
this can be replicated with a ZIP that includes more than 15 files inside and using the /rebuils/zipfile endpoint
The machine takes too much time to process the files, therefore throws timeout:600 error. which was not an issue before

**Comment by mohitsengarr** [comment]
@Lestat06 Can you please provide the sample zip? I have tried with this and working.
[15+.zip](https://github.com/k8-proxy/cs-k8s-api/files/6790179/15%2B.zip)

**Comment by mohitsengarr** [comment]
@Lestat06 I have tested both files 
[pdf+img.zip](https://github.com/k8-proxy/cs-k8s-api/files/6800277/pdf%2Bimg.zip)
[pdf+img-encrypted.zip](https://github.com/k8-proxy/cs-k8s-api/files/6800295/pdf%2Bimg-encrypted.zip)
provided by you and these files are successfully processed. If you are getting the timeout error on specific server. We can increase the processing timeout, Because it could be possible that minio/classic icap take longer time for the large file. We have an environment variable `"ProcessingTimeoutDuration": "HH:MM:SS"` to update the processing time.

Here are the postman screenshots of both files.

zip file:
![zip](https://user-images.githubusercontent.com/43764140/125266815-d6151b00-e323-11eb-9539-8a3ad8c06353.png)

protected zip file:
![protectedZip](https://user-images.githubusercontent.com/43764140/125266834-db726580-e323-11eb-942a-492daa1f6132.png)

@GINAGC

**Comment by Lestat06** [comment]
@mohitsengarr actually just tried this on develop and it works. however in version 0.6.0 still still throws timeout error

**Comment by mohitsengarr** [comment]
@Lestat06 you have to ask from the devops to update the timeout.

**Comment by GINAGC** [comment]
@Lestat06 please review this, ask Himanshu or Pranay to support on updating timeout.

**Comment by Lestat06** [comment]
@GINAGC @mohitsengarr  tested this in develop and it seems its working now.
