### ISSUE TITLE
GW cloud SDK initial training 

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/cs-k8s-api#473]
Good morning @Swathi Yerabolu your initial task is to:

1. Review all information under section “GW Cloud SDK” and understand how this product work. https://k8-proxy.github.io/k8-proxy-documentation/docs/products/gw%20cloud%20sdk/a-overview
2. Write a set of requirements (simple list) with the list of functionality that the cloud SDK supports.
3. Review latest release and deploy the AMIs: https://github.com/k8-proxy/cs-k8s-api/releases/tag/v0.6.0 - @Marti Kekesi (Upwork - Operations Coordinator) please help us with the access to AWS playground.
4. After that, I will assign some issues for QA. 

After your initial review of the documentation, we can have a meeting to discuss any questions.

**Comment by SwathiYerabolu** [comment]
GW cloud SDK is used to rebuild a file and removes malicious content.
The file types that are accepted are the following
- Word (doc, dot, docx, dotx, docm, dotm)
- Excel(xls, xlt, xlm, xlsx, xlsm, xltx, xltm, xlam)
- PowerPoint(ppt, pot, pps, pptx, potx, ppsx, pptm, potm, ppsm, ppam)
- PDF
- Images(JPEG, PNG, GIF, EMF, WMF, TIFF, GeoTIFF, BMP)
- Audio(WAV, MP3)
- Video(MPG, MP4)
- Portable executables(PE, DLL, MUI, EXE, MACH-0, COFF, ELF)

Looking a the endpoints, It can also do the following apart from rebuilding the above supported files.
- Request for health check of the file.
- Detects file type
- Xml report file after the rebuild process is done
- Can rebuild base64 encoded file.
- Rebuilds files inside ZipFiles, protected ZipFiles(both binary and base64)
- Analyse a file using binary data, base64 encoded representation
- Returns the version of API and SDK engine

It returns a response after the rebuild.
- Unprocessable(Not supported or cannot be rebuild)
- Cleaned(When rebuild is successful)
- Clean(The file is already clean)
- Expired(Upon license expiry)
- Internal_error(Error in Minio-ICAP processing)

We can also do this for a single file or multiple files, the api will take care of processing several files at once instead of us doing it one by one.

Deployed the instance for the latest build(v0.6.0) from AWS
